// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHTqnAn21WsrdOHo8nqsSnUwyPb1SIsEQ',
    appId: '1:660606682501:web:32764761628211b127b0ec',
    messagingSenderId: '660606682501',
    projectId: 'food-app-c2fe8',
    authDomain: 'food-app-c2fe8.firebaseapp.com',
    storageBucket: 'food-app-c2fe8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6vjmdqwOy4Yz9SHQ-OLw5TgDTKTpNW-k',
    appId: '1:660606682501:android:5bb210b0bcaefc5f27b0ec',
    messagingSenderId: '660606682501',
    projectId: 'food-app-c2fe8',
    storageBucket: 'food-app-c2fe8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiPmUBx4yPIF0DvGEJJQVs0S-VHLj1QZk',
    appId: '1:660606682501:ios:551515d56b903be327b0ec',
    messagingSenderId: '660606682501',
    projectId: 'food-app-c2fe8',
    storageBucket: 'food-app-c2fe8.firebasestorage.app',
    iosBundleId: 'com.example.foodUserApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiPmUBx4yPIF0DvGEJJQVs0S-VHLj1QZk',
    appId: '1:660606682501:ios:551515d56b903be327b0ec',
    messagingSenderId: '660606682501',
    projectId: 'food-app-c2fe8',
    storageBucket: 'food-app-c2fe8.firebasestorage.app',
    iosBundleId: 'com.example.foodUserApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHTqnAn21WsrdOHo8nqsSnUwyPb1SIsEQ',
    appId: '1:660606682501:web:8b6bcfd6d132179427b0ec',
    messagingSenderId: '660606682501',
    projectId: 'food-app-c2fe8',
    authDomain: 'food-app-c2fe8.firebaseapp.com',
    storageBucket: 'food-app-c2fe8.firebasestorage.app',
  );
}
